baseURL = 'https://ivanrusanov.github.io/'
languageCode = 'en-us'
title = 'Ivan Rusanov'

theme = 'hugo-bearblog'

enableRobotsTXT = true

disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]
[permalinks]
  blog = "/:slug/"
  tags = "/blog/:slug"

[params]
  hideMadeWithLine = true
